myapp/urls.py
from . import views
from django.contrib import admin
from django.urls import path, include,re_path
from django.conf.urls import url
from myapp import views

urlpatterns = [
    path('', views.homey, name ="homey"),
	path('product/<int:shoe_id>', views.shoe_page, name="productt"),
    path('search', views.search,name="search"),
    path('product_list/<int:cat_id>', views.product_list,name="product_list"),
    path('product_list_type/<int:type_id>', views.product_list_type,name="product_list_type"),
    path('product_list_cat_type/<int:cat_id>/<int:type_id>', views.product_list_cat_type,name="product_list_cat_type"),
    path('brand_list/<int:bra_id>', views.brand_list,name="brand_list"),
    path('checkout/', views.checkout, name="checkout"),
    path('confirm/', views.confirm, name="confirm"),
    path('cart/', views.cart, name="cart"),
    path('add_to_cart/', views.add_to_cart, name="add_to_cart"),    
   
    path('about/', views.about, name="about"),
    path('help/', views.help, name="help"),
    path('sell/', views.sell, name="sell"),

    path('NewArrival/', views.new_arrival, name="NewArrival"),
    path('NewArrival_01/', views.new_arrival01, name="new_arrival01"),
    path('NewArrival_02/', views.new_arrival02, name="new_arrival02"),

    path('checkout_process_guest', views.checkout_process_guest),

    path('oauth/', include('social_django.urls', namespace='social')),
]


snea/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings
from myapp import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('myapp.urls')),
    
    path('signup/', views.registerPage, name="signup"),
    path('login/', views.loginPage, name="login"),
    path('logout/', views.logoutUser, name="logout"),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

myapp/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Brand(models.Model):
    name = models.CharField(max_length=45)

    def __str__(self):
        return self.name

class Category(models.Model):
    title = models.CharField(max_length=45)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse('product:product_by_category', args=[self.title])


class Type(models.Model):
    type = models.CharField(max_length=30)


    def __str__(self):
        return self.type


class Product(models.Model):
    model = models.CharField(max_length=100)
    description = models.TextField(null=True, blank=True)
    brand = models.ForeignKey(Brand, related_name="models", on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, related_name="types", on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    image_1 = models.ImageField(null=True, blank=True ,upload_to="product/1")
    image_2 = models.ImageField(null=True, blank=True ,upload_to="product/2")
    image_3 = models.ImageField(null=True, blank=True ,upload_to="product/3")
    image_4 = models.ImageField(null=True, blank=True ,upload_to="product/4")
    is_feature = models.BooleanField(default=False)
    seller = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

    def __str__(self):
        return self.model
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('product', arg[str(self.id)])
        
class Size(models.Model):
    size = models.DecimalField(max_digits=3, decimal_places=1)

    def __str__(self):
        return '%s' %(self.size)

class ProductAttribute(models.Model):
    product = models.ForeignKey(Product,on_delete=models.CASCADE)
    brand = models.ForeignKey(Brand,on_delete=models.CASCADE)
    size = models.ForeignKey(Size,on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    type = models.ForeignKey(Type, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=8, decimal_places=2)
    

    def __str__(self):
        return self.product.model

class ShoeSize(models.Model):
    size = models.DecimalField(max_digits=3, decimal_places=1)
    inventory = models.IntegerField(default=0)
    quantity_sold = models.IntegerField(default=0)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)

    def __str__(self):
        return '%s' %(self.size)

class Cart(models.Model):
    total = models.DecimalField(max_digits=8, decimal_places=2)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class CartItem(models.Model):
    shoe = models.ForeignKey(ShoeSize, on_delete=models.CASCADE)
    quantity = models.IntegerField()
    cart = models.ForeignKey(Cart,related_name="cart_items",on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now=True)




class Address(models.Model):
    address = models.CharField(max_length=45)
    address2 = models.CharField(max_length=45)
    city = models.CharField(max_length=45)
    state = models.CharField(max_length=2)
    zipcode = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField(max_length=254)
    password = models.CharField(max_length=60)
    created_at = models.DateTimeField(auto_now_add= True)
    updated_at = models.DateTimeField(auto_now= True)

class CreditCard(models.Model):
    number = models.IntegerField()
    security_code = models.IntegerField()
    expiration_date = models.DateField()
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    address = models.ForeignKey(Address, related_name="card", on_delete = models.CASCADE)
    user = models.ForeignKey(User, related_name="credit_cards", on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now_add= True)
    updated_at = models.DateTimeField(auto_now= True)

class Order(models.Model):
    status = models.CharField(max_length=45)
    cart = models.OneToOneField(
        Cart,
        on_delete=models.CASCADE
    )
    user = models.ForeignKey(User,related_name="orders", on_delete=models.CASCADE)
    credit_card = models.ForeignKey(CreditCard,related_name="orders", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add= True)
    updated_at = models.DateTimeField(auto_now= True)

myapp/forms.py
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms

class CreateUserForm(UserCreationForm):
	class Meta:
		model = User
		fields = ['username', 'email', 'password1', 'password2']

myapp/views.py
from django.shortcuts import render
from .models import *
from django.views.generic.detail import DetailView
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login, logout
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.generic import TemplateView
from django.contrib.auth.mixins import LoginRequiredMixin
from .forms import CreateUserForm
from django.http import HttpResponse
from django.forms import inlineformset_factory
from django.shortcuts import redirect
import datetime

# Create your views here.

class HomeView(LoginRequiredMixin, TemplateView):
    template_name = "myapp/facebook.html" 

def homey(request):
	data = Product.objects.all().order_by('id')[0:4]
	dat = Product.objects.all().order_by('id')[4:8]
	da = Product.objects.all().order_by('id')[8:12]
	categoryy = Category.objects.all()
	brands = Brand.objects.all()
	cats = Product.objects.distinct().values('category__title')


	context = {
		'data':data,
		'categoryy':categoryy,
		'brands':brands,
		'cats':cats,
		'dat':dat,
		'da':da
	}

	return render(request, 'myapp/homey.html',context)

def search(request):
	q=request.GET['q']
	data=Product.objects.filter(model__icontains=q)
	return render(request,'myapp/search.html',{'data':data})



def shoe_page(request, shoe_id,):
	if 'cart' not in request.session:
		cart = Cart.objects.create(total=0)
		request.session['cart']=cart.id

	brand = Brand.objects.all()
	shoe = Product.objects.get(id=shoe_id)
	brands = Brand.objects.all()

	


	context = {
		'shoe': Product.objects.get(id=shoe_id),
		'brand' : brand,
		'brands' : brands
	}

	return render(request, 'myapp/product.html', context)

def product_list(request,cat_id):
	category=Category.objects.get(id=cat_id)
	data=Product.objects.filter(category=category)
	brands = Brand.objects.all()
	
	categoryy = Category.objects.all()
	return render(request,'myapp/product_list.html',{
			'data':data,
			'category':category,
			'cat_id':cat_id,
			'brands':brands,
			'mode':1
			})

def product_list_type(request,type_id):
	type=Type.objects.get(id=type_id)
	data=Product.objects.filter(type=type)
	brands = Brand.objects.all()
	
	categoryy = Category.objects.all()
	return render(request,'myapp/product_list.html',{
			'data':data,
			'type_id':type_id,
			'brands':brands,
			'mode':2
			})

def product_list_cat_type(request,cat_id,type_id):
	category=Category.objects.get(id=cat_id)
	type=Type.objects.get(id=type_id)
	print(type_id)
	data=Product.objects.filter(category=category)
	data= data.filter(type=type)
	print(data)
	brands = Brand.objects.all()
	
	categoryy = Category.objects.all()
	return render(request,'myapp/product_list.html',{
			'data':data,
			'category':category,
			'cat_id':cat_id,
			'type_id':type_id,
			'brands':brands,
			'mode':3
			})

def brand_list(request,bra_id):
	brand = Brand.objects.get(id=bra_id)
	data = Product.objects.filter(brand=brand)
	brands = Brand.objects.all()
	
	return render(request, 'myapp/brand_list.html', {'data':data,'brand':brand,'brands':brands})

def new_arrival(request):
	brands = Brand.objects.all()
	context = {'brands':brands}
	return render(request, 'myapp/new_arrival.html', context)

def new_arrival01(request):
	brands = Brand.objects.all()
	context = {'brands':brands}
	return render(request, 'myapp/new_arrival01.html', context)

def new_arrival02(request):
	brands = Brand.objects.all()
	context = {'brands':brands}
	return render(request, 'myapp/new_arrival02.html', context)

def refresh_cart_total(cart):
    total = 0
    for item in cart.cart_items.all():
        total += item.quantity * item.shoe.product.price
    cart.total = total
    cart.save()


def add_to_cart(request):
	shoe = ShoeSize.objects.get(id=request.POST['size_id'])
	cart = Cart.objects.get(id=request.session['cart_id'])
	quantity = request.POST['quantity']
	cart_item = CartItem.objects.create(shoe=shoe, quantity=quantity,cart=cart)
	context = {
		'cart': Cart.objects.get(id=request.session['cart_id']),
		'shoe':shoe,
		'cart_item':cart_item
	}
	return render(request, 'myapp/cart.html', context)

	refresh_cart_total(cart)
	return redirect('/cart')


def cart(request):
	if 'card_id' not in request.session:
		cart = Cart.objects.create(total=1)
		request.session['cart_id']=cart.id
	context = {
		'cart': Cart.objects.get(id=request.session['cart_id'])
	}
	return render(request, 'myapp/cart.html', context)

def checkout(request):
	if 'cart_id' not in request.session:
		return redirect("/")

	cart = Cart.objects.get(id=request.session['cart_id'])


	
	context = {
		'cart' : Cart.objects.get(id=request.session["cart_id"])
	}

	return render(request, 'myapp/checkout.html', context)

def checkout_process_guest(request):
	shipping_address = Address.objects.create(
		address = request.POST['address'],
		address2 = request.POST['address2'],
		city = request.POST['city'],
		state = request.POST['state'],
		zipcode = request.POST['zipcode'],
	)

	if 'same_address' in request.POST:
		billing_address = shipping_address
		cc_first_name = request.POST['first_name']
		cc_last_name = request.POST['last_name']
	else :
		billing_address = Address.objects.create(
			address = request.POST['cc_address'],
			address2 = request.POST['cc_address2'],
			city = request.POST['cc_city'],
			state = request.POST['cc_state'],
			zipcode = request.POST['cc_zipcode'],
		)
	cc_first_name = request.POST['cc_first_name']
	cc_last_name = request.POST['cc_last_name']

	guest_user = User.objects.create(
		first_name = request.POST['first_name'],
		last_name = request.POST['last_name'],
		email = request.POST['email'],
		password = "",
		
	)

	expiration_date = datetime.date(int(request.POST['expireYYYY']),int(request.POST['expireM']),1)

	credit_card = CreditCard.objects.create(
		number = request.POST['cc_number'],
		security_code = request.POST['cc_security_code'],
		expiration_date = expiration_date,
		first_name = cc_first_name,
		last_name = cc_last_name,
		address = billing_address,
		user = guest_user,
	)

	cart = Cart.objects.get(id=request.session['cart_id'])
	new_order = Order.objects.create(
		status = "Processing",
		cart = cart,
		user = guest_user,
		credit_card = credit_card,
	)

	for item in cart.cart_items.all():
		shoe = item.shoe
		shoe.inventory = shoe.inventory-item.quantity
		shoe.quantity_sold = shoe.quantity_sold+item.quantity
		shoe.save()

	request.session['order_id'] = new_order.id

	request.session.pop("cart_id")

	return redirect('confirm')


def confirm(request):
    # Retrieves order from session.
    current_order = Order.objects.get(id = request.session['order_id'])

    # Formats credit card number to just show last digits.
    # This may be a security vulnerability. Not sure.
    cc_last_digits = current_order.credit_card.number % 10000

    # Because credit card expiration date is stored as a date with the first of the month,
    # this reformats it as a MM/YY
    cc_expiration_date = current_order.credit_card.expiration_date.strftime('%m/%y')

    context = {
        'order': current_order,
        'cc_last_digits': cc_last_digits,
        'cc_expiration_date': cc_expiration_date
    }
    return render(request, 'myapp/confirm.html', context)

def about(request):
	brands = Brand.objects.all()
	context = {'brands':brands}
	return render(request, 'myapp/about.html', context)

def help(request):
	brands = Brand.objects.all()
	context = {'brands':brands}
	return render(request, 'myapp/help.html', context)

def sell(request):
	brands = Brand.objects.all()
	context = {'brands':brands}
	return render(request, 'myapp/sell.html', context)

#login-regis

from .forms import CreateUserForm

def registerPage(request):
	if request.user.is_authenticated:
		context = {}
		return render(request, 'myapp/signup.html', context)
	else:
		form = CreateUserForm()
		if request.method == 'POST':
			form = CreateUserForm(request.POST)
			if form.is_valid():
				form.save()
				user = form.cleaned_data.get('username')
				messages.success(request, 'Account was created for ' + user)

				return redirect('login')

		context = {'form':form}
		return render(request, 'myapp/signup.html', context)

def loginPage(request):
	if request.user.is_authenticated:
		context = {}
		return render(request, 'myapp/login.html', context)
	else:
		if request.method == 'POST':
			username = request.POST.get('username')
			password =request.POST.get('password')

			user = authenticate(request, username=username, password=password)

			if user is not None:
				login(request, user)
				return redirect('homey')
			else:
				messages.info(request, 'Username OR password is incorrect')

		context = {}
		return render(request, 'myapp/login.html', context)

def logoutUser(request):
	logout(request)
	return redirect('login')

@login_required(login_url='login')
def home(request):
	return render(request, 'myapp/homey.html', context)

myapp/templates/myapp/about.html
{% extends 'myapp/main.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>About Us</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    
    <link rel = "stylesheet" type="text/css" href="{% static 'css/arrival.css' %}">
    <link rel = "stylesheet" type="text/css" href="{% static 'css/news.css' %}">
  
  </head>

    <div class="About">

        </div>
        <div class="banner">
            <img src = "https://i.pinimg.com/originals/60/5c/6b/605c6b6f01dd565b4fe8c773d8ec1eb1.jpg" alt="" width=100% height=10% >
        </div>
        
        <br>
        <br>
        <br>
        <div class="container pt1">
        <br>
                <img src = "https://i.pinimg.com/originals/6b/e1/c9/6be1c9c4124f22cc02086b15f45abea0.jpg" alt=""  width=100% height=100% ></img>
        </div>
        
        <div class="container bg-dark ">
            <hr  size="6" width="100%"   />
        </div>
        
        
        <div class="container pt1">
            <br>
            <img src = "https://i.pinimg.com/originals/a7/93/23/a79323f42c2de39a6679fd8176af59f9.jpg" alt="" width=100% height=100%></imgimg>
        </div>
        
        <div class="container bg-dark ">
            <hr  size="6" width="100%"   />
        </div>
        
        <div class="container-fluid">
            <img src = "https://i.pinimg.com/originals/f4/65/45/f46545bd88a158e854aaccedbfebc3d1.jpg" alt=""  ></imgimg>
        </div>
        <div>
            <img src = "https://i.pinimg.com/originals/3b/5c/c1/3b5cc1448560a2d2df512f863045c157.jpg" alt="" width=100% height=100%></imgimg>
        </div>   
      </div>

{% endblock content %}

myapp/templates/myapp/help.html
{% extends 'myapp/main.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HELP</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    
    <link rel = "stylesheet" type="text/css" href="{% static 'css/arrival.css' %}">
    <link rel = "stylesheet" type="text/css" href="{% static 'css/news.css' %}">
  
  </head>

<style>
    body,

    html {
        margin: 0;
        padding: 0;
        height: 100%;
    }
    .user_card {
        margin-top: auto;
        margin-bottom: auto;
        background: #ffffff;
        position: relative;
        display: flex;
        justify-content: center;
        flex-direction: column;
        border-radius: 5%;
        border: 4px solid #000000;
        width: 600px;
        height: 500px; 
    }

    .form_container {
        margin-top: 0%;
    }

    .help_list{
        text-align: center;
        margin-top: 4%;
        margin-bottom: 4%;
        color: black;
        text-decoration: none;
        margin-left: 7%;
    }

    .button {
        border: none;
        color: white;
        padding: 5px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        font-size: 25px;
        margin-top: 8%;
        margin-left: 8%;
        margin-bottom: 0%;
        cursor: pointer;
        width: 85%;
        font-family: Arial;
    }

    .button1 {background-color: #262626;}
</style>

<br><br><br><br><br>
    <div class="container h-100">
		<div class="d-flex justify-content-center h-100">
			<div class="user_card">
                    <span><a href="#" class="help_list">How do I contact customer service and when can I expect to hear back?</a></span>
                    <hr style="width:85%;height:1px;color:rgb(180, 180, 180);background-color:rgb(114, 114, 114);margin-top: 3%;margin-left: 7%;">
                    <span><a href="#" class="help_list">How long does it take to receive my order?</a></span>
                    <hr style="width:85%;height:1px;color:rgb(180, 180, 180);background-color:rgb(114, 114, 114);margin-top: 3%;margin-left: 7%;">
                    <span><a href="#" class="help_list">What is a Bid and how do i buy on sneakersX?</a></span>
                    <hr style="width:85%;height:1px;color:rgb(180, 180, 180);background-color:rgb(114, 114, 114);margin-top: 3%;margin-left: 7%;">
                    <span><a href="#" class="help_list">What is an Ask and how do i sell on sneakersX?</a></span>
                    <hr style="width:85%;height:1px;color:rgb(180, 180, 180);background-color:rgb(114, 114, 114);margin-top: 3%;margin-left: 7%;">
                    <span><a href="#" class="help_list">My Bid/Ask just got accepted. Can I cancle it?</a></span>

                    <span><a href="#"><button class="button button1">Contact Us</button></a></span>
            </div>
        </div>
    </div>
    <br><br><br><br><br>

    {% endblock content %}

myapp/templates/myapp/product.html
{% extends 'myapp/main.html' %}
{% load static %}
{% block content %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HOME</title>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    
  </head>
<body>

    <div class="container" style="margin-top:3%;">
        <nav aria-label="breadcrumb ">
            <ol class="breadcrumb ">
              <li class="breadcrumb-item "><a href="{% url 'homey' %}" class="text-reset" style="text-decoration: none; font-family: Roboto; font-size: 16px;">Homepage</a></li>
              <li class="breadcrumb-item active" aria-current="page" style="font-family: Roboto; font-size: 16px;">{{shoe.brand}} / {{shoe.model}}</li>
            </ol>
        </nav>
    </div>

    
    <div class="container">
        <div class="row mb-3">
            <div class="col-md-8 themed-grid-col ">
 
                <div class="row row-cols-1 row-cols-md-2 g-4" style="margin-top: 20px; margin-left: 20px;">

                    <div class="col">
                        <img id="zoom_01" data-zoom-image="{{ show.image_1.url }}"src="{{ shoe.image_1.url }}" alt="">
                    </div>
                    <div class="col">
                        <img src="{{ shoe.image_2.url }}" alt="">
                    </div>
                    <div class="col">
                        <img src="{{ shoe.image_3.url }}" alt="">
                    </div>
                    <div class="col">
                        <img src="{{ shoe.image_4.url }}" alt="">
                    </div>

                </div>
            </div>

            <div class="col-md-4 themed-grid-col ">
                <div class="container " style="margin-top: -50px;">
                    <br><br><br><br>
                    <p class="text-center fs-2 fw-bold">{{shoe.brand}} </p>
                    <p class="text-center fs-2 fw-bold">{{shoe.model}} </p>
                </div>

                <div class="container detail" style="margin-top: 70px;">
                    <p>DETAIL</p>
                    <p>{{shoe.description}}</p>
                </div>

                <button type="button" class="btn btn-light btn-lg pr fs-2 disabled"  tabindex="-1" role="button" aria-disabled="true"> <p style="color: black;"> {{shoe.price|floatformat:0}} THB</p></button>
                <div class="container " style="margin-top: 0px;">

                    <form action="/add_to_cart/" method="POST">
                        
                        {% csrf_token %}
                        <label for="sizes" class="fs-3" style="font-size: 36px; color: #000000;">Sizes</label> &nbsp;
                        <span>
                            <select name="size_id" id="sizes" 
                            style="border: 2px solid rgb(180, 180, 180); width: 100px; height:30px; margin-top:15px;border-radius: 15px;">
                                {% for m in shoe.shoesize_set.all %}
                                {% if m.inventory > 0 %}
                                <option value="{{m.id}}" > &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; {{m.size}}</option>
                                {% else %}
                                <option disabled>{{m.size} Sold Out}</option>
                                {% endif %}
                                {% endfor %}
                            </select>
                        </span>
                        
                        <div class="form-group" style="margin-top: 20px;">
                            <div class="input-group input-spinner" style="width: 280px; ">

                                <input type="hidden" >
                                <input type="number"  name="quantity" value="1" class="form-control" id="addToCartBtn" > &nbsp;

                                <a href="{% url 'cart' %}"><input type="submit" value="Add Cart" class="btn btn-dark add-btn update-cart" style="margin-top: 0px;"></a>

                            </div>  
                        </div>
                        


                    </form>
                </div>
                        
            </div>
            
        </div>
        
    </div>
    <br><br>

    <hr style="width: 80%;margin-left: 10%;position: relative;">


    <br><br>
    
</body>
</html>   

{% endblock %}
